_extends: github-settings:.github/settings.yml

repository:
  name: helloolololo
  description: hellooo test thingy here

labels:
  - name: DO NOT MERGE
    color: '#ef5350'
    description: An issue with the system ğŸ›.
